### ISSUE TITLE
Adapter for GitHub releases

### ISSUE THREAD

**Issue by mnapoli** [stevewest/changelog#17]
It would be useful to have an adapter that uses the GitHub API.

The changelog would be generated by fetching all the releases, e.g. here https://github.com/stevewest/changelog/releases

Could be used for example here: https://github.com/CouscousPHP/Couscous/issues/84

**Comment by stevewest** [comment]
So I have been having a think about this and wondering what the most useful behaviour would be. My initial thinking is that when you construct a change log the adaptor will read every release and build a full log from that. Then when saving the changes the adaptor will add any new releases and update any releases that have been updated.

Thoughts?

**Comment by mnapoli** [comment]
> when you construct a change log the adaptor will read every release and build a full log from that.

Yep sounds good.

> Then when saving the changes the adaptor will add any new releases and update any releases that have been updated.

You mean that the adapter will write/update GitHub releases? I wasn't expecting that (and will not be using that feature) but why not. Will it be used by anyone though?

**Comment by stevewest** [comment]
Well it makes sense to me that if you can read from GH releases you can write back to them if you want to make changes. It should not be too tricky to do (famous last words).

**Comment by stevewest** [comment]
Just about to start work on this. I'll do it in two halves.

 - [ ] Read from GitHub releases api to generate a `Log`
 - [ ] Write changes back to the releases api

Once the first half is pushed up you should be able to use it for what you want. I'll update you when that has been pushed.

**Comment by mnapoli** [comment]
:+1: awesome

**Comment by stevewest** [comment]
@mnapoli The fix has been pushed now so the latest dev-master should do what you need now.

**Comment by mnapoli** [comment]
@stevewest thanks I am pretty swamped this week but hopefully sooner than later I'll add that to Couscous. Anyway it will happen :)

**Comment by stevewest** [comment]
Let me know if you encounter any bugs and I'll try to get them fixed asap for you.

**Comment by stevewest** [comment]
Closing this issue as I will open a separate one for writing back to the Github API, that requires a lot more thought to be able to do it sensibly.
