### ISSUE TITLE
The composer constraint should not force using dev-master

### ISSUE THREAD

**Issue by stof** [stevewest/changelog#21]
This constraint forbids using stable versions of the package and so makes it a pain for people using it as composer only allows stable versions by default (see https://github.com/composer/composer/issues/5211)

Thus, depending on ``dev-master`` is equivalent to depending on +Inf as version of the package. It is an unbound constraint. This means that your code would break if the ``naneau/semver`` package releses a new major version (so not BC) as you will always use whatever new major version comes out for existing releases of your package.

**Comment by stevewest** [comment]
Not sure how that got past me, thanks for reporting it. (I also had no idea anyone was even using this package)

**Comment by stof** [comment]
@stevewest you could add a run of ``composer validate --strict`` as part of your CI, which would catch such mistake

**Comment by stevewest** [comment]
Thanks, I did not know that existed, I'll add that in to my `.travis.yml`

**Comment by stevewest** [comment]
Added in https://github.com/stevewest/changelog/pull/22

**Comment by spekulatius** [comment]
Hello @stevewest and @stof 

thanks for raising this on "my behalf" @stof ! And yes @stevewest, I have played a bit around and this https://github.com/spekulatius/PainfreeReleases/ came out ;)

Cheers,
Peter

**Comment by gitamitgit** [comment]
Thanks, it get useful for me :)
