### ISSUE TITLE
CLI script

### ISSUE THREAD

**Issue by stevewest** [stevewest/changelog#6]
Include a cli script to allow change logs to be manipulated via the command line.

Potential tasks:
 - [x] Convert between formats
 - [x] Make a major/minor/patch release (this would change "unreleased" to the next version number)
 - [ ] Add a change to a release

Other:
 - [x] Load config file from working directory or specified at runtime for IO configs

**Comment by sagikazarmark** [comment]
It probably worth mentioning that [gushphp](http://gushphp.org) is a good project maintainer tool, might be a good place for integration. Also, they are working on an extension interface which includes some sort of DI solution, which might be a good example for you: gushphp/gush#386

**Comment by stevewest** [comment]
I'm all for supporting plugins for other projects but I am not quite sure what ChangeLog could provide for gush. (And possibly this should be a new issue :stuck_out_tongue: )

**Comment by sagikazarmark** [comment]
:+1:
